config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'
  get 'welcome/news' => 'welcome#news', as: :news
  get 'welcome/swipe' => 'welcome#swipe'
  get 'charities/map' => 'charities#map_locations'

  get 'charities/login' => 'charities#identify', as: "charities_login"
  post 'charities/login' => 'charities#login'
  get 'charities/logout' => 'charities#destroy'

  resources :categories

  resources :users

  resources :charities do
    resources :wishlists
  end

  #Custom routes for search
  resources :search, only: [:index]

  #routes for sessions
  get 'users/login' => 'users#login'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'


  get 'charities/:id/profile' => 'charities#profile', as: :profile
  get '/about' => 'welcome#about'
  get '/categories/:id/interest' =>'categories#interest', as: :interest

  get 'charities/:id/star' => 'charities#star', as: :star
  get 'charities/:id/recently_visited' => 'charities#recently_visited', as: :recently_visited

  get 'charities/:id/map' => 'charities#map_location'


  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, presence: true
  validates_uniqueness_of :email
  validates :email, presence: true

  has_many :users_charities
  has_many :charities, through: :users_charities
  has_many :interests
  has_many :categories, through: :interests
  has_many :users_items
  has_many :items, through: :users_items
  has_many :visitations
  has_many :visited_charities, through: :visitations, source: :charity

  after_create :set_slug

  has_secure_password

  # geocoded_by :ipaddress, latitude: :lat, longitude: :lon
  # after_validation :geocode

  def recently_visited_charities
    self.visited_charities.order('created_at DESC').uniq.limit(5)
  end

  def visit_charity(charity)
    self.visited_charities << charity
    self.save
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def set_slug
    self.slug = self.username.downcase.split.join("-") + "-" + self.id.to_s
    self.save
  end

  def to_param
    self.slug
  end

  def recommended_charity
    if self.charities.length > 1
      match_weights = User.establish_match_weights(self.id)
      charity_scores = self.set_charity_scores(match_weights)
      recommend_charity_id = key_with_highest_value(charity_scores)
      Charity.find(recommend_charity_id)
    else
      Charity.all.sample
    end
  end

  def self.establish_match_weights(user_id)
    user = User.find(user_id)
    common_likes = UsersCharity.where(charity_id: user.charity_ids).pluck(:user_id, :charity_id)
    overlap_per_user = common_likes.group_by{ |user_id, charity_id| user_id }.map { |k, v| [k, v.length] }
  end

  def set_charity_scores(user_weights)
    charity_scores = {}
    Charity.all.each{|charity| charity_scores[charity.id] = 0}
    user_weights.each do |user_id, user_value|
      User.find(user_id).charities.each do |charity|
        charity_scores[charity.id] += user_value unless self.charities.include?(charity)
      end
    end
    return charity_scores
  end

  def key_with_highest_value(hash)
    hash.max_by{|k,v| v}[0]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      session[:user_id] = @user.id
      session[:charity_id] = nil
      redirect_to '/'
    else
      @error = "Invalid Registration"
      render :new
    end
  end

  def show
    @user = User.find_by(slug: params[:id])
    if current_user == @user
      @starred_charities = current_user.charities
      @visited_charities = current_user.recently_visited_charities
      @categories = current_user.categories
      @recommended_charity = current_user.recommended_charity
    else
      redirect_to root_path
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
  <div class="ui vertical stripe segment">
    <div class="ui six column centered grid">
      <div class="six wide column">
        <div class="ui teal inverted segment">
           
           <h1>Sign Up</h1>

				<%= form_for :user, url: '/users', :html => {:class => "ui form"} do |f| %>
				
				Username: <%= f.text_field :username, class: 'field' %>
				<BR>
				
				  Email: <%= f.text_field :email, class: 'field' %>
				
				  Password: <%= f.password_field :password, class: 'field' %>
				<BR><BR>
				  <%= f.submit "Submit", class: 'ui button' %>
				 
				<% end %>
			
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<br>
<br>
<br>
      <h2 class="ui icon header">
        <i class="user icon"></i>
      <h1><%= @user.username.capitalize %>'s Profile</h1>
      <div class="ui grid">

      <div class="six wide column">
      <% if @starred_charities %>
        <h3>Starred Charities</h3
          <% @starred_charities.each do |charity| %>
             <p><%= link_to charity.name, charity_path(charity) %></p>
          <% end %>
      <% end %>
      </div>

      <div class="four wide centered text column">
      <% if @categories %>
        <h3>Your Interest Categories</h3>
          <% @categories.each do |category| %>
            <p><%= link_to category.name, category_path(category) %></p>
          <% end %>
      <% end %>
      </div>

      <div class="six wide column">
      <% if @visited_charities %>
        <h3>Recently Viewed Charities</h3>
        <% if @visited_charities.length > 4 %>
          <% @visited_charities[-5..-1].each do |charity| %>
            <p><%= link_to charity.name, charity_path(charity) %></p>
          <% end %>
        <% else %>
          <% @visited_charities.each do |charity| %>
            <p><%= link_to charity.name, charity_path(charity) %></p>
          <% end %>
       <% end %>
      <% end %>
      </div>


      <div class="eight wide centered column">
        <h3>Recommended Charity:</h3>
        <p><%= link_to @recommended_charity.name, charity_path(@recommended_charity) %></p>
        <p><%= @recommended_charity.description %></p>
    </div>
  </div>