config/routes.rb
Rails.application.routes.draw do


  root 'welcome#index'
  get 'welcome/news' => 'welcome#news', as: :news
  get 'welcome/swipe' => 'welcome#swipe'
  get 'charities/map' => 'charities#map_locations'

  get 'charities/login' => 'charities#identify', as: "charities_login"
  post 'charities/login' => 'charities#login'
  get 'charities/logout' => 'charities#destroy'

  resources :categories

  resources :users

  resources :charities do
    resources :wishlists
  end

  #Custom routes for search
  resources :search, only: [:index]

  #routes for sessions
  get 'users/login' => 'users#login'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'


  get 'charities/:id/profile' => 'charities#profile', as: :profile
  get '/about' => 'welcome#about'
  get '/categories/:id/interest' =>'categories#interest', as: :interest

  get 'charities/:id/star' => 'charities#star', as: :star
  get 'charities/:id/recently_visited' => 'charities#recently_visited', as: :recently_visited

  get 'charities/:id/map' => 'charities#map_location'


  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/charity.rb
class Charity < ActiveRecord::Base


  # validates_presence_of :contact_email, presence: true
  validates_presence_of :password_digest, presence: true


  has_many :users, through: :users_charities
  has_many :users_charities
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :wishlists
  has_many :items, through: :wishlists
  has_many :visitations
  has_many :visiting_users, through: :visitations, source: :user

  before_create :add_downcase_name
  after_create :set_slug

  geocoded_by :address_string
  after_validation :geocode, :if => :address_string_changed?

  has_secure_password


  def add_downcase_name
    self.downcase_name = name.downcase
  end

  def address_string
    street_address + ", " + city + ", " + state + " " + zip_code
  end

  def address_string_changed?
    street_address_changed? || city_changed? || state_changed? || zip_code_changed?
  end

  def set_slug
    self.slug = self.name.downcase.split.join("-") + "-" + self.id.to_s
    self.save
  end

  def to_param
    self.slug
  end

end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  def new
    @charity = Charity.new
  end

  def identify
    @charity = Charity.new
  end

  def login
    @charity = Charity.find_by_contact_email(params[:contact_email])
    
    if @charity && @charity.authenticate(params[:password])
      session[:charity_id] = @charity.id
      session[:user_id] = nil
      redirect_to charity_path(@charity)
    else
      render :identify
      @error = "Invalid Login"
    end
  end

  def edit
    @charity = Charity.find_by(slug: params[:id])
    redirect_to '/' if current_user != @charity
  end

  def update
    @charity = Charity.find_by(slug: params[:id])
    if @charity.update(charity_params)
      redirect_to '/'
    else
      @errors = "There was a problem updating your information, please make sure all fields are entered."
      render :edit
    end

  end

  def destroy
    session[:charity_id] = nil
    redirect_to '/'
  end

  def create
    @charity = Charity.new(charity_params)
    if @charity.save
      session[:charity_id] = @charity.id
      session[:user_id] = nil
      redirect_to charity_path(@charity)
    else
      @error = "There was a problem entering in your information, please try again."
      render :new
    end
  end

  def profile
    @charity = Charity.find_by(slug: params[:id])
    redirect_to '/' if current_user != @charity
    @wishlist = @charity.wishlists.last
    @wishlist.update_wishlist if @wishlist
  end

  def show
    @charity = Charity.find_by(slug: params[:id])
    @wishlist = @charity.wishlists.last
    @wishlist.update_wishlist if @wishlist
    # if @wishlist && @wishlist.length < 1
    #   @errors = "This particular Amazon wishlist page uses a less common format and is not renderable at this time."
    # end
    if current_user.class == User
      current_user.visit_charity(@charity)
    end

  end

  def star
    @charity = Charity.find_by(slug: params[:id])
    if current_user.charities.include?(@charity)
      users_charity = UsersCharity.find_by user:current_user, charity: @charity
      users_charity.destroy
    else
      current_user.charities << @charity
      current_user.save
    end
    redirect_to charity_path(@charity)
  end

  def recently_visited
  end

  def map_location
    @charity = Charity.find_by(slug: params[:id])
    respond_to do |format|
      format.html
      format.json { render json: @charity }
    end
  end

  def map_locations
    @charities = Charity.all.select { |charity| charity.latitude != nil }
    respond_to do |format|
      format.html
      format.json { render json: @charities }
    end
  end

  private

  def charity_params
    params.require(:charity).permit(:name, :description, :category, :zip_code, :contact_name, :twitter_handle, :donation_page, :website, :contact_email, :contact_phone, :street_address, :city, :state, :password, category_ids: [])
  end


end

   

 

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/edit.html.erb
<div class="ui vertical stripe segment">
    <div class="ui eight column centered grid">
        <div class="eight wide column">
            <div class="ui teal inverted segment">

              <h1>Edit charity information:</h1>

              <%= form_for @charity, :html => {:class => "ui form"} do |f| %>
                <%= f.label :charity_name %>:
                <%= f.text_field :name %><br />

                <%= f.label :description %>:
              	<%= f.text_area :description, :rows => 4, :cols => 50, :placeholder => "Description of charity...." %><br>

                <%= f.label :choose_your_charity_categories %>:
                <%= f.select :category_ids, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %><br>

                <%= f.label :contact_name %>:
                <%= f.text_field :contact_name %><br />

                <%= f.label :contact_email %>:
                <%= f.text_field :contact_email %><br />

                <%= f.label :contact_phone %>:
                <%= f.text_field :contact_phone %><br />

                <%= f.label :street_address %>:
                <%= f.text_field :street_address %><br />

                <%= f.label :city %>:
                <%= f.text_field :city, class: 'field' %><br />

                <%= f.label :state %>:
                <%= f.text_field :state, :placeholder => "two letter abbreviation" %><br />

                <%= f.label :zip_code %>:
                <%= f.text_field :zip_code %><br />

                <%= f.label :password %>:
                <%= f.password_field :password %><br />
                <p></p>
                <%= f.submit "Submit", class: 'ui button' %>
              <% end %>

              <% if @error %>
                <p><%= @error %></p>
              <% end %>

      </div>
    </div>
  </div>
</div>

app/views/charities/identify.html.erb
  <div class="ui vertical stripe segment">
    <div class="ui six column centered grid">
      <div class="six wide column">
        <div class="ui teal inverted segment">
           
           <h1>Charity Login</h1>

        <%= form_tag charities_login_path, method: :post, class: "ui form" do %>
        
          Email: <%= text_field_tag :contact_email, nil, class: 'field' %>
          <BR>
          
            Password: <%= password_field_tag :password, nil, class: 'field' %>
          <BR><BR>
            <%= submit_tag "Submit", class: 'ui button' %>
         
        <% end %>
      
        </div>
      </div>
    </div>
  </div>

app/views/charities/map_locations.html.erb
<%= stylesheet_link_tag "map.css" %>
<br>
<br>
<br>
<br>
<br>
<br>


<form id="search-zip-form">
  <label for="search-zip">Enter 5-digit zip code:</label></br><br>
  <input type="text" name="search-zip"></br></br>
  <button class="ui primary button" type="submit">Find Charities</button>
</form>
<br>
<div id="error-container"></div>

<div id="full-map-canvas"></div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="ui stackable grid">
  <div class="eight wide left aligned column">
    <div class="left floated">
      <div id="left-side">
      </div>
    </div>
  </div>

  <div class="eight wide left aligned column">
    <div class="right floated">
    </div>
  </div>
</div>

app/views/charities/new.html.erb
   <div class="ui vertical stripe segment">
        <div class="ui eight column centered grid">
            <div class="eight wide column">
                <div class="ui teal inverted segment">
                <% if @error %>
                      <p><%= @error %></p>
                    <% end %>
                    <h1>List your
                    charity:</h1>
                    <%= form_for @charity, :html => {:class => "ui form"} do |f| %>
                    <%= f.label :charity_name %>:
                    <%= f.text_field :name, class: 'field' %><br>
                    <%= f.label :charity_description %>:
                    <%= f.text_area :description, :rows => 4, :cols => 50, :placeholder => "Your mission statement, needs, etc..." %><br>
                    <%= f.label :choose_your_charity_categories %>:
                    <%= f.select :category_ids, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %><br>

                    <%= f.label :contact_name %>:
                    <%= f.text_field :contact_name, class: 'field' %><br>
                    <%= f.label :contact_email %>:
                    <%= f.text_field :contact_email, class: 'field' %><br>
                    <%= f.label :contact_phone %>:
                    <%= f.text_field :contact_phone, class: 'field' %><br>
                    <%= f.label :twitter_handle %>:
                    <%= f.text_field :twitter_handle %><br>
                    <%= f.label :website %>:
                    <%= f.text_field :website %><br>
                    <%= f.label :donation_page %>:
                    <%= f.text_field :donation_page %><br>
                    <%= f.label :street_address %>:
                    <%= f.text_field :street_address %><br>
                    <%= f.label :city %>:
                    <%= f.text_field :city %><br>
                    <%= f.label :state %>:
                    <%= f.text_field :state, :placeholder => "two letter abbreviation" %><br>
                    <%= f.label :zip_code %>:
                    <%= f.text_field :zip_code %><br>
                    <%= f.label :password %>:
                    <%= f.password_field :password %><br><BR>
                    <%= f.submit "Sign Up", class: 'ui button' %>
                    <% end %>

                    
                </div>
            </div>
        </div>
    </div>

    

app/views/charities/profile.html.erb
<br>
<br>
<br>
<br>
<br>
      <h2 class="ui icon header">
        <i class="dashboard icon"></i>
      <h1><%= @charity.name %>'s Dashboard</h1>
      <br>
      <br>
      <br>
      <div class="ui grid">
      <div class="six wide column">
      <% if true %>
        <h3> Edit Charity Information</h3
        <ul>
         <%= form_for @charity, :html => {:class => "ui form"} do |f| %>
                <%= f.label :charity_name %>:
                <%= f.text_field :name %><br />

                <%= f.label :description %>:
                <%= f.text_area :description, :rows => 4, :cols => 50, :placeholder => "Description of charity...." %><br>

                <%= f.label :choose_your_charity_categories %>:
                <%= f.select :category_ids, Category.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %><br>

                <%= f.label :contact_name %>:
                <%= f.text_field :contact_name %><br />

                <%= f.label :contact_email %>:
                <%= f.text_field :contact_email %><br />

                <%= f.label :contact_phone %>:
                <%= f.text_field :contact_phone %><br />

                <%= f.label :street_address %>:
                <%= f.text_field :street_address %><br />

                <%= f.label :city %>:
                <%= f.text_field :city, class: 'field' %><br />

                <%= f.label :state %>:
                <%= f.text_field :state, :placeholder => "two letter abbreviation" %><br />

                <%= f.label :zip_code %>:
                <%= f.text_field :zip_code %><br />

                <%= f.label :password %>:
                <%= f.password_field :password %><br />
                <p></p>
                <%= f.submit "Submit", class: 'ui button' %>
              <% end %>
          
        </ul>
      <% end %>
      </div>
      <div class="four wide column">
        <div id="ajaxify">

          <% if @wishlist && @wishlist.items.count > 0 %>
            <h3><%= link_to "Update Amazon Wishlist", new_charity_wishlist_path(@charity), class: "wishlist-class", :ajax_path => new_charity_wishlist_path(@charity) %></h3>
          <% end %>
        </div>
       
      </div>
      <div class="six wide column">
      
      <% if !@wishlist %>
       <h3><%= link_to "Add Amazon Wishlist", new_charity_wishlist_path(@charity), class: "wishlist-class", :ajax_path => new_charity_wishlist_path(@charity) %></h3><br>

       <h3><a target="_blank" href="https://www.amazon.com/wishlist/universal">What's an Amazon Wishlist?</a></h3><br>


      <% else %>

        <h3>Current Amazon Wishlist</h3>
        <ul>
        <% if @wishlist && @wishlist.items.count > 0 %>
                    <% @wishlist.items.each do |item|  %>
                        <p><img src="<%= item.picture_url %>"><a href="<%= @wishlist.original_link %>"><%= item.name %></a>, Price: <%= item.current_price %>, Priority: <%= item.priority %>, Requested Quantity: <%= item.qty_requested %>, Quanity Received: <%= item.qty_received %></p><br>
                    <% end %>
                <% end %>

          
        </ul>
      <% end %>
      </div>

app/views/charities/show.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript">
    loadMap();
  </script>
<% end %>
<%= stylesheet_link_tag "map.css" %>


<br>
<br>
<br>
<br>
<br>
<br>
<br>


<div class="ui stackable grid">
  <div class="eight wide left aligned column">
    <div class="left floated">
      <div id="left-side">
        <% if @errors %>
       	 <p><%= @errors  %></p>
        <% end %>

        <h1><%= @charity.name %><% if session[:user_id] %>
        <% if current_user.charities.include?(@charity) %>
          <a id="star" href="/charities/<%= @charity.to_param %>/star"><i id="star_icon" class="large yellow star icon"></i></a>
        <% else %>
          <a id="star" href="/charities/<%= @charity.to_param %>/star"><i id="star_icon" class="large yellow empty star icon"></i></a>
        <% end %>
        <% end %>
        </h1>

				<div class="charity-info"
          <p><%= @charity.street_address %>, <%= @charity.city %>, <%= @charity.state %>, <%= @charity.zip_code %> </p>
        </div>

		    <div id="map-canvas"></div>
      </div>
    </div>
  </div>

  <div class="eight wide left aligned column">
    <div class="right floated">
			<br>
			<br>
			<h3>Charity Overview:</h3>
			<div class="charity-info"
			  <p> <%= @charity.description %></p>
        <% if @charity.website %>
          <a target="_blank" href="<%= @charity.website %>"><button class="ui primary button" id="override">Visit <%= @charity.name %><i class="right arrow icon"></i></button></a>    		
        <% end %>
      </div>
		</div>
  </div>
</div>

<br>
<br>

<% if @wishlist && @wishlist.items.count > 0 %>
   <div class="ui grid">
      <div class="sixteen wide left aligned column">
        <div class="left floated">
          <h3>Amazon Wishlist:</h3>
          <table class="ui very basic collapsing celled table">
            <thead>
              <tr><th></th>
              <th class="six wide">Item</th>
              <th>Price</th>
              <th>Priority</th>
              <th>Requested Qty</th>
              <th>Qty Received</th>
              </tr></thead>

            <tbody>
					    <% @wishlist.items.each do |item|  %>
                <tr>
                  <td>
                    <img src="<%= item.picture_url %>">
                  </td>
                  <td>
                    <a target="_blank" href="<%= @wishlist.original_link %>"><%= item.name %></a>
                  </td>
                  <td>
                    <%= item.current_price %>
                  </td>
                  <td>
                    <%= item.priority %>
                  </td>
                  <td>
                  	<%= item.qty_requested %>
                  </td>
                  <td>
                  	<%= item.qty_received %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>

        </div>
      </div>
    </div>
<% end %>